# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cn_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cn_msg.proto',
  package='node',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x63n_msg.proto\x12\x04node\"y\n\x0b\x43\x32N_Request\x12\x34\n\x10\x63lientConnectReq\x18\x01 \x01(\x0b\x32\x1a.node.C2N_ClientConnectReq\x12\x34\n\x10\x63lientDisconnReq\x18\x02 \x01(\x0b\x32\x1a.node.C2N_ClientDisconnReq\"\xaf\x01\n\x0cN2C_Response\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x11\n\terrorCode\x18\x02 \x01(\x05\x12\x10\n\x08\x65rrorStr\x18\x03 \x01(\t\x12\x34\n\x10\x63lientConnectRes\x18\x04 \x01(\x0b\x32\x1a.node.N2C_ClientConnectRes\x12\x34\n\x10\x63lientDisconnRes\x18\x05 \x01(\x0b\x32\x1a.node.N2C_ClientDisconnRes\"7\n\x14\x43\x32N_ClientConnectReq\x12\x11\n\tisService\x18\x01 \x01(\x08\x12\x0c\n\x04guid\x18\x02 \x01(\x04\"$\n\x14N2C_ClientConnectRes\x12\x0c\n\x04guid\x18\x01 \x01(\x04\"\x16\n\x14\x43\x32N_ClientDisconnReq\"\x16\n\x14N2C_ClientDisconnRes*\x80\x01\n\x06\x43N_Msg\x12\x1c\n\x16\x43\x32N_Client_Connect_Req\x10\x81\x80\x0c\x12\x1c\n\x16N2C_Client_Connect_Res\x10\x82\x80\x0c\x12\x1c\n\x16\x43\x32N_Client_Disconn_Req\x10\x83\x80\x0c\x12\x1c\n\x16N2C_Client_Disconn_Res\x10\x84\x80\x0c\x42\x1a\n\x18\x63om.kongyt.node.messages')
)

_CN_MSG = _descriptor.EnumDescriptor(
  name='CN_Msg',
  full_name='node.CN_Msg',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='C2N_Client_Connect_Req', index=0, number=196609,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='N2C_Client_Connect_Res', index=1, number=196610,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2N_Client_Disconn_Req', index=2, number=196611,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='N2C_Client_Disconn_Res', index=3, number=196612,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=467,
  serialized_end=595,
)
_sym_db.RegisterEnumDescriptor(_CN_MSG)

CN_Msg = enum_type_wrapper.EnumTypeWrapper(_CN_MSG)
C2N_Client_Connect_Req = 196609
N2C_Client_Connect_Res = 196610
C2N_Client_Disconn_Req = 196611
N2C_Client_Disconn_Res = 196612



_C2N_REQUEST = _descriptor.Descriptor(
  name='C2N_Request',
  full_name='node.C2N_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientConnectReq', full_name='node.C2N_Request.clientConnectReq', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientDisconnReq', full_name='node.C2N_Request.clientDisconnReq', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=143,
)


_N2C_RESPONSE = _descriptor.Descriptor(
  name='N2C_Response',
  full_name='node.N2C_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='node.N2C_Response.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='node.N2C_Response.errorCode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorStr', full_name='node.N2C_Response.errorStr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientConnectRes', full_name='node.N2C_Response.clientConnectRes', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientDisconnRes', full_name='node.N2C_Response.clientDisconnRes', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=321,
)


_C2N_CLIENTCONNECTREQ = _descriptor.Descriptor(
  name='C2N_ClientConnectReq',
  full_name='node.C2N_ClientConnectReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isService', full_name='node.C2N_ClientConnectReq.isService', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='guid', full_name='node.C2N_ClientConnectReq.guid', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=378,
)


_N2C_CLIENTCONNECTRES = _descriptor.Descriptor(
  name='N2C_ClientConnectRes',
  full_name='node.N2C_ClientConnectRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='node.N2C_ClientConnectRes.guid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=416,
)


_C2N_CLIENTDISCONNREQ = _descriptor.Descriptor(
  name='C2N_ClientDisconnReq',
  full_name='node.C2N_ClientDisconnReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=440,
)


_N2C_CLIENTDISCONNRES = _descriptor.Descriptor(
  name='N2C_ClientDisconnRes',
  full_name='node.N2C_ClientDisconnRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=464,
)

_C2N_REQUEST.fields_by_name['clientConnectReq'].message_type = _C2N_CLIENTCONNECTREQ
_C2N_REQUEST.fields_by_name['clientDisconnReq'].message_type = _C2N_CLIENTDISCONNREQ
_N2C_RESPONSE.fields_by_name['clientConnectRes'].message_type = _N2C_CLIENTCONNECTRES
_N2C_RESPONSE.fields_by_name['clientDisconnRes'].message_type = _N2C_CLIENTDISCONNRES
DESCRIPTOR.message_types_by_name['C2N_Request'] = _C2N_REQUEST
DESCRIPTOR.message_types_by_name['N2C_Response'] = _N2C_RESPONSE
DESCRIPTOR.message_types_by_name['C2N_ClientConnectReq'] = _C2N_CLIENTCONNECTREQ
DESCRIPTOR.message_types_by_name['N2C_ClientConnectRes'] = _N2C_CLIENTCONNECTRES
DESCRIPTOR.message_types_by_name['C2N_ClientDisconnReq'] = _C2N_CLIENTDISCONNREQ
DESCRIPTOR.message_types_by_name['N2C_ClientDisconnRes'] = _N2C_CLIENTDISCONNRES
DESCRIPTOR.enum_types_by_name['CN_Msg'] = _CN_MSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

C2N_Request = _reflection.GeneratedProtocolMessageType('C2N_Request', (_message.Message,), dict(
  DESCRIPTOR = _C2N_REQUEST,
  __module__ = 'cn_msg_pb2'
  # @@protoc_insertion_point(class_scope:node.C2N_Request)
  ))
_sym_db.RegisterMessage(C2N_Request)

N2C_Response = _reflection.GeneratedProtocolMessageType('N2C_Response', (_message.Message,), dict(
  DESCRIPTOR = _N2C_RESPONSE,
  __module__ = 'cn_msg_pb2'
  # @@protoc_insertion_point(class_scope:node.N2C_Response)
  ))
_sym_db.RegisterMessage(N2C_Response)

C2N_ClientConnectReq = _reflection.GeneratedProtocolMessageType('C2N_ClientConnectReq', (_message.Message,), dict(
  DESCRIPTOR = _C2N_CLIENTCONNECTREQ,
  __module__ = 'cn_msg_pb2'
  # @@protoc_insertion_point(class_scope:node.C2N_ClientConnectReq)
  ))
_sym_db.RegisterMessage(C2N_ClientConnectReq)

N2C_ClientConnectRes = _reflection.GeneratedProtocolMessageType('N2C_ClientConnectRes', (_message.Message,), dict(
  DESCRIPTOR = _N2C_CLIENTCONNECTRES,
  __module__ = 'cn_msg_pb2'
  # @@protoc_insertion_point(class_scope:node.N2C_ClientConnectRes)
  ))
_sym_db.RegisterMessage(N2C_ClientConnectRes)

C2N_ClientDisconnReq = _reflection.GeneratedProtocolMessageType('C2N_ClientDisconnReq', (_message.Message,), dict(
  DESCRIPTOR = _C2N_CLIENTDISCONNREQ,
  __module__ = 'cn_msg_pb2'
  # @@protoc_insertion_point(class_scope:node.C2N_ClientDisconnReq)
  ))
_sym_db.RegisterMessage(C2N_ClientDisconnReq)

N2C_ClientDisconnRes = _reflection.GeneratedProtocolMessageType('N2C_ClientDisconnRes', (_message.Message,), dict(
  DESCRIPTOR = _N2C_CLIENTDISCONNRES,
  __module__ = 'cn_msg_pb2'
  # @@protoc_insertion_point(class_scope:node.N2C_ClientDisconnRes)
  ))
_sym_db.RegisterMessage(N2C_ClientDisconnRes)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.kongyt.node.messages'))
# @@protoc_insertion_point(module_scope)
