# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: element_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='element_msg.proto',
  package='node',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x65lement_msg.proto\x12\x04node\"I\n\nElementMsg\x12\r\n\x05msgId\x18\x01 \x01(\x05\x12\x0f\n\x07\x65leFrom\x18\x02 \x01(\x04\x12\r\n\x05\x65leTo\x18\x03 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"\x13\n\x04Helo\x12\x0b\n\x03txt\x18\x01 \x01(\t*\x17\n\x07\x45le_Msg\x12\x0c\n\x08\x45le_Helo\x10\x01\x42\x1a\n\x18\x63om.kongyt.node.messages')
)

_ELE_MSG = _descriptor.EnumDescriptor(
  name='Ele_Msg',
  full_name='node.Ele_Msg',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Ele_Helo', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=123,
  serialized_end=146,
)
_sym_db.RegisterEnumDescriptor(_ELE_MSG)

Ele_Msg = enum_type_wrapper.EnumTypeWrapper(_ELE_MSG)
Ele_Helo = 1



_ELEMENTMSG = _descriptor.Descriptor(
  name='ElementMsg',
  full_name='node.ElementMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgId', full_name='node.ElementMsg.msgId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eleFrom', full_name='node.ElementMsg.eleFrom', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eleTo', full_name='node.ElementMsg.eleTo', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='node.ElementMsg.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=100,
)


_HELO = _descriptor.Descriptor(
  name='Helo',
  full_name='node.Helo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txt', full_name='node.Helo.txt', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['ElementMsg'] = _ELEMENTMSG
DESCRIPTOR.message_types_by_name['Helo'] = _HELO
DESCRIPTOR.enum_types_by_name['Ele_Msg'] = _ELE_MSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ElementMsg = _reflection.GeneratedProtocolMessageType('ElementMsg', (_message.Message,), dict(
  DESCRIPTOR = _ELEMENTMSG,
  __module__ = 'element_msg_pb2'
  # @@protoc_insertion_point(class_scope:node.ElementMsg)
  ))
_sym_db.RegisterMessage(ElementMsg)

Helo = _reflection.GeneratedProtocolMessageType('Helo', (_message.Message,), dict(
  DESCRIPTOR = _HELO,
  __module__ = 'element_msg_pb2'
  # @@protoc_insertion_point(class_scope:node.Helo)
  ))
_sym_db.RegisterMessage(Helo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.kongyt.node.messages'))
# @@protoc_insertion_point(module_scope)
